---
plugins:
  duplication:
    enabled: true
  eslint:
    enabled: true
    channel: 'eslint-7'
    config:
      extensions:
        - .js
        - .jsx
        - .ts
        - .tsx
    checks:
      '@typescript-eslint/no-explicit-any':
        enabled: false
  fixme:
    enabled: true
  nodesecurity:
    enabled: true
ratings:
  paths:
    - '**.js'
    - '**.jsx'
    - '**.md'
    - '**.ts'
    - '**.tsx'
exclude_paths:
  - .expo/
  - .github/
  - assets/
  - coverage/
  - docs/
  - node_modules/
  - scripts/
  - src/config/
  - __tests__/**/__snapshots__
  - __maestro__/
  - patches/
  - .codeclimate.yml
  - publiccode.yml
  - .eslintrc
  - .gitignore
  - .nvmrc
  - .yvmrc
  - babel.config.js
  - '*.png'
  - '*.jpg'
  - '*.tmpl'
  - '*.json'
  - '*.txt'
  - '*.ttf'
  - '*.gif'
  - jest-setup.js
  - yarn.lock
checks:
  similar-code:
    enabled: false
  identical-code:
    enabled: false
