env:
  browser: true
  es6: true
  jest: true
  node: true
extends:
  - 'eslint:recommended'
  - 'plugin:react/recommended'
  - 'plugin:@typescript-eslint/recommended'
  - 'prettier/@typescript-eslint'
  - 'plugin:prettier/recommended'
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
  __DEV__: true
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module
plugins:
  - import
  - react
  - react-native
  - '@typescript-eslint'
rules:
  arrow-parens:
    - error
    - always
  comma-dangle:
    - error
    - never
  complexity:
    - error
    - 11
  func-names:
    - error
    - as-needed
  linebreak-style:
    - error
    - unix
  no-console:
    - error
    - allow:
      - warn
      - error
  no-unused-vars:
    - 0
  quotes:
    - error
    - single
  semi:
    - error
    - always
  react/display-name:
    - off
  import/no-cycle:
    - error
    - maxDepth: 1
  import/order:
    - error
    - newlines-between: always
  react-native/no-unused-styles:
    - error
  react-native/no-inline-styles:
    - error
  react-native/no-color-literals:
    - error
  '@typescript-eslint/no-unused-vars':
    - 2
  '@typescript-eslint/explicit-module-boundary-types':
    - 0
settings:
  react:
    version: detect
  import/extensions:
    - .js
    - .jsx
    - .ts
    - .tsx
  import/parsers:
    '@typescript-eslint/parser':
      - .ts
      - .tsx
