export const countries = [
  { id: 4, name: 'AF', value: 'Afghanistan' },
  { id: 818, name: 'EG', value: 'Ägypten' },
  { id: 8, name: 'AL', value: 'Albanien' },
  { id: 12, name: 'DZ', value: 'Algerien' },
  { id: 20, name: 'AD', value: 'Andorra' },
  { id: 24, name: 'AO', value: 'Angola' },
  { id: 28, name: 'AG', value: 'Antigua und Barbuda' },
  { id: 226, name: 'GQ', value: 'Äquatorialguinea' },
  { id: 32, name: 'AR', value: 'Argentinien' },
  { id: 51, name: 'AM', value: 'Armenien' },
  { id: 31, name: 'AZ', value: 'Aserbaidschan' },
  { id: 231, name: 'ET', value: 'Äthiopien' },
  { id: 36, name: 'AU', value: 'Australien' },
  { id: 44, name: 'BS', value: 'Bahamas' },
  { id: 48, name: 'BH', value: 'Bahrain' },
  { id: 50, name: 'BD', value: 'Bangladesch' },
  { id: 52, name: 'BB', value: 'Barbados' },
  { id: 112, name: 'BY', value: 'Belarus' },
  { id: 56, name: 'BE', value: 'Belgien' },
  { id: 84, name: 'BZ', value: 'Belize' },
  { id: 204, name: 'BJ', value: 'Benin' },
  { id: 64, name: 'BT', value: 'Bhutan' },
  { id: 68, name: 'BO', value: 'Bolivien' },
  { id: 70, name: 'BA', value: 'Bosnien und Herzegowina' },
  { id: 72, name: 'BW', value: 'Botswana' },
  { id: 76, name: 'BR', value: 'Brasilien' },
  { id: 96, name: 'BN', value: 'Brunei' },
  { id: 100, name: 'BG', value: 'Bulgarien' },
  { id: 854, name: 'BF', value: 'Burkina Faso' },
  { id: 108, name: 'BI', value: 'Burundi' },
  { id: 152, name: 'CL', value: 'Chile' },
  { id: 156, name: 'CN', value: 'Volksrepublik China' },
  { id: 188, name: 'CR', value: 'Costa Rica' },
  { id: 208, name: 'DK', value: 'Dänemark' },
  { id: 276, name: 'DE', value: 'Deutschland' },
  { id: 212, name: 'DM', value: 'Dominica' },
  { id: 214, name: 'DO', value: 'Dominikanische Republik' },
  { id: 262, name: 'DJ', value: 'Dschibuti' },
  { id: 218, name: 'EC', value: 'Ecuador' },
  { id: 384, name: 'CI', value: 'Elfenbeinküste' },
  { id: 222, name: 'SV', value: 'El Salvador' },
  { id: 232, name: 'ER', value: 'Eritrea' },
  { id: 233, name: 'EE', value: 'Estland' },
  { id: 748, name: 'SZ', value: 'Eswatini' },
  { id: 242, name: 'FJ', value: 'Fidschi' },
  { id: 246, name: 'FI', value: 'Finnland' },
  { id: 250, name: 'FR', value: 'Frankreich' },
  { id: 266, name: 'GA', value: 'Gabun' },
  { id: 270, name: 'GM', value: 'Gambia' },
  { id: 268, name: 'GE', value: 'Georgien' },
  { id: 288, name: 'GH', value: 'Ghana' },
  { id: 308, name: 'GD', value: 'Grenada' },
  { id: 300, name: 'GR', value: 'Griechenland' },
  { id: 320, name: 'GT', value: 'Guatemala' },
  { id: 324, name: 'GN', value: 'Guinea' },
  { id: 624, name: 'GW', value: 'Guinea-Bissau' },
  { id: 328, name: 'GY', value: 'Guyana' },
  { id: 332, name: 'HT', value: 'Haiti' },
  { id: 340, name: 'HN', value: 'Honduras' },
  { id: 356, name: 'IN', value: 'Indien' },
  { id: 360, name: 'ID', value: 'Indonesien' },
  { id: 368, name: 'IQ', value: 'Irak' },
  { id: 364, name: 'IR', value: 'Iran' },
  { id: 372, name: 'IE', value: 'Irland' },
  { id: 352, name: 'IS', value: 'Island' },
  { id: 376, name: 'IL', value: 'Israel' },
  { id: 380, name: 'IT', value: 'Italien' },
  { id: 388, name: 'JM', value: 'Jamaika' },
  { id: 392, name: 'JP', value: 'Japan' },
  { id: 887, name: 'YE', value: 'Jemen' },
  { id: 400, name: 'JO', value: 'Jordanien' },
  { id: 116, name: 'KH', value: 'Kambodscha' },
  { id: 120, name: 'CM', value: 'Kamerun' },
  { id: 124, name: 'CA', value: 'Kanada' },
  { id: 132, name: 'CV', value: 'Kap Verde' },
  { id: 398, name: 'KZ', value: 'Kasachstan' },
  { id: 634, name: 'QA', value: 'Katar' },
  { id: 404, name: 'KE', value: 'Kenia' },
  { id: 417, name: 'KG', value: 'Kirgisistan' },
  { id: 296, name: 'KI', value: 'Kiribati' },
  { id: 170, name: 'CO', value: 'Kolumbien' },
  { id: 174, name: 'KM', value: 'Komoren' },
  { id: 180, name: 'CD', value: 'Kongo, Demokratische Republik' },
  { id: 178, name: 'CG', value: 'Kongo, Republik' },
  { id: 408, name: 'KP', value: 'Korea, Nord' },
  { id: 410, name: 'KR', value: 'Korea, Süd' },
  { id: 191, name: 'HR', value: 'Kroatien' },
  { id: 192, name: 'CU', value: 'Kuba' },
  { id: 414, name: 'KW', value: 'Kuwait' },
  { id: 418, name: 'LA', value: 'Laos' },
  { id: 426, name: 'LS', value: 'Lesotho' },
  { id: 428, name: 'LV', value: 'Lettland' },
  { id: 422, name: 'LB', value: 'Libanon' },
  { id: 430, name: 'LR', value: 'Liberia' },
  { id: 434, name: 'LY', value: 'Libyen' },
  { id: 438, name: 'LI', value: 'Liechtenstein' },
  { id: 440, name: 'LT', value: 'Litauen' },
  { id: 442, name: 'LU', value: 'Luxemburg' },
  { id: 450, name: 'MG', value: 'Madagaskar' },
  { id: 454, name: 'MW', value: 'Malawi' },
  { id: 458, name: 'MY', value: 'Malaysia' },
  { id: 462, name: 'MV', value: 'Malediven' },
  { id: 466, name: 'ML', value: 'Mali' },
  { id: 470, name: 'MT', value: 'Malta' },
  { id: 504, name: 'MA', value: 'Marokko' },
  { id: 584, name: 'MH', value: 'Marshallinseln' },
  { id: 478, name: 'MR', value: 'Mauretanien' },
  { id: 480, name: 'MU', value: 'Mauritius' },
  { id: 484, name: 'MX', value: 'Mexiko' },
  { id: 583, name: 'FM', value: 'Mikronesien' },
  { id: 498, name: 'MD', value: 'Moldau' },
  { id: 492, name: 'MC', value: 'Monaco' },
  { id: 496, name: 'MN', value: 'Mongolei' },
  { id: 499, name: 'ME', value: 'Montenegro' },
  { id: 508, name: 'MZ', value: 'Mosambik' },
  { id: 104, name: 'MM', value: 'Myanmar' },
  { id: 516, name: 'NA', value: 'Namibia' },
  { id: 520, name: 'NR', value: 'Nauru' },
  { id: 524, name: 'NP', value: 'Nepal' },
  { id: 554, name: 'NZ', value: 'Neuseeland' },
  { id: 558, name: 'NI', value: 'Nicaragua' },
  { id: 528, name: 'NL', value: 'Niederlande' },
  { id: 562, name: 'NE', value: 'Niger' },
  { id: 566, name: 'NG', value: 'Nigeria' },
  { id: 807, name: 'MK', value: 'Nordmazedonien' },
  { id: 578, name: 'NO', value: 'Norwegen' },
  { id: 512, name: 'OM', value: 'Oman' },
  { id: 40, name: 'AT', value: 'Österreich' },
  { id: 626, name: 'TL', value: 'Osttimor' },
  { id: 586, name: 'PK', value: 'Pakistan' },
  { id: 585, name: 'PW', value: 'Palau' },
  { id: 591, name: 'PA', value: 'Panama' },
  { id: 598, name: 'PG', value: 'Papua-Neuguinea' },
  { id: 600, name: 'PY', value: 'Paraguay' },
  { id: 604, name: 'PE', value: 'Peru' },
  { id: 608, name: 'PH', value: 'Philippinen' },
  { id: 616, name: 'PL', value: 'Polen' },
  { id: 620, name: 'PT', value: 'Portugal' },
  { id: 646, name: 'RW', value: 'Ruanda' },
  { id: 642, name: 'RO', value: 'Rumänien' },
  { id: 643, name: 'RU', value: 'Russland' },
  { id: 90, name: 'SB', value: 'Salomonen' },
  { id: 894, name: 'ZM', value: 'Sambia' },
  { id: 882, name: 'WS', value: 'Samoa' },
  { id: 674, name: 'SM', value: 'San Marino' },
  { id: 678, name: 'ST', value: 'São Tomé und Príncipe' },
  { id: 682, name: 'SA', value: 'Saudi-Arabien' },
  { id: 752, name: 'SE', value: 'Schweden' },
  { id: 756, name: 'CH', value: 'Schweiz' },
  { id: 686, name: 'SN', value: 'Senegal' },
  { id: 688, name: 'RS', value: 'Serbien' },
  { id: 690, name: 'SC', value: 'Seychellen' },
  { id: 694, name: 'SL', value: 'Sierra Leone' },
  { id: 716, name: 'ZW', value: 'Simbabwe' },
  { id: 702, name: 'SG', value: 'Singapur' },
  { id: 703, name: 'SK', value: 'Slowakei' },
  { id: 705, name: 'SI', value: 'Slowenien' },
  { id: 706, name: 'SO', value: 'Somalia' },
  { id: 724, name: 'ES', value: 'Spanien' },
  { id: 144, name: 'LK', value: 'Sri Lanka' },
  { id: 659, name: 'KN', value: 'St. Kitts und Nevis' },
  { id: 662, name: 'LC', value: 'St. Lucia' },
  { id: 670, name: 'VC', value: 'St. Vincent und die Grenadinen' },
  { id: 710, name: 'ZA', value: 'Südafrika' },
  { id: 729, name: 'SD', value: 'Sudan' },
  { id: 728, name: 'SS', value: 'Südsudan' },
  { id: 740, name: 'SR', value: 'Surivalue' },
  { id: 760, name: 'SY', value: 'Syrien' },
  { id: 762, name: 'TJ', value: 'Tadschikistan' },
  { id: 834, name: 'TZ', value: 'Tansania' },
  { id: 764, name: 'TH', value: 'Thailand' },
  { id: 768, name: 'TG', value: 'Togo' },
  { id: 776, name: 'TO', value: 'Tonga' },
  { id: 780, name: 'TT', value: 'Trinidad und Tobago' },
  { id: 148, name: 'TD', value: 'Tschad' },
  { id: 203, name: 'CZ', value: 'Tschechien' },
  { id: 788, name: 'TN', value: 'Tunesien' },
  { id: 792, name: 'TR', value: 'Türkei' },
  { id: 795, name: 'TM', value: 'Turkmenistan' },
  { id: 798, name: 'TV', value: 'Tuvalu' },
  { id: 800, name: 'UG', value: 'Uganda' },
  { id: 804, name: 'UA', value: 'Ukraine' },
  { id: 348, name: 'HU', value: 'Ungarn' },
  { id: 858, name: 'UY', value: 'Uruguay' },
  { id: 860, name: 'UZ', value: 'Usbekistan' },
  { id: 548, name: 'VU', value: 'Vanuatu' },
  { id: 862, name: 'VE', value: 'Venezuela' },
  { id: 784, name: 'AE', value: 'Vereinigte Arabische Emirate' },
  { id: 840, name: 'US', value: 'Vereinigte Staaten' },
  { id: 826, name: 'GB', value: 'Vereinigtes Königreich' },
  { id: 704, name: 'VN', value: 'Vietnam' },
  { id: 140, name: 'CF', value: 'Zentralafrikanische Republik' },
  { id: 196, name: 'CY', value: 'Zypern' }
];
