export const countryList = [
  { name: 'AF', value: 'Afghanistan', id: '004' },
  { name: 'AL', value: 'Albania', id: '008' },
  { name: 'DZ', value: 'Algeria', id: '012' },
  { name: 'AS', value: 'American Samoa', id: '016' },
  { name: 'AD', value: 'Andorra', id: '020' },
  { name: 'AO', value: 'Angola', id: '024' },
  { name: 'AI', value: 'Anguilla', id: '660' },
  { name: 'AQ', value: 'Antarctica', id: '010' },
  { name: 'AG', value: 'Antigua and Barbuda', id: '028' },
  { name: 'AR', value: 'Argentina', id: '032' },
  { name: 'AM', value: 'Armenia', id: '051' },
  { name: 'AW', value: 'Aruba', id: '533' },
  { name: 'AU', value: 'Australia', id: '036' },
  { name: 'AT', value: 'Austria', id: '040' },
  { name: 'AZ', value: 'Azerbaijan', id: '031' },
  { name: 'BS', value: 'Bahamas (the)', id: '044' },
  { name: 'BH', value: 'Bahrain', id: '048' },
  { name: 'BD', value: 'Bangladesh', id: '050' },
  { name: 'BB', value: 'Barbados', id: '052' },
  { name: 'BY', value: 'Belarus', id: '112' },
  { name: 'BE', value: 'Belgium', id: '056' },
  { name: 'BZ', value: 'Belize', id: '084' },
  { name: 'BJ', value: 'Benin', id: '204' },
  { name: 'BM', value: 'Bermuda', id: '060' },
  { name: 'BT', value: 'Bhutan', id: '064' },
  { name: 'BO', value: 'Bolivia (Plurinational State of)', id: '068' },
  { name: 'BQ', value: 'Bonaire, Sint Eustatius and Saba', id: '535' },
  { name: 'BA', value: 'Bosnia and Herzegovina', id: '070' },
  { name: 'BW', value: 'Botswana', id: '072' },
  { name: 'BV', value: 'Bouvet Island', id: '074' },
  { name: 'BR', value: 'Brazil', id: '076' },
  { name: 'IO', value: 'British Indian Ocean Territory (the)', id: '086' },
  { name: 'BN', value: 'Brunei Darussalam', id: '096' },
  { name: 'BG', value: 'Bulgaria', id: '100' },
  { name: 'BF', value: 'Burkina Faso', id: '854' },
  { name: 'BI', value: 'Burundi', id: '108' },
  { name: 'CV', value: 'Cabo Verde', id: '132' },
  { name: 'KH', value: 'Cambodia', id: '116' },
  { name: 'CM', value: 'Cameroon', id: '120' },
  { name: 'CA', value: 'Canada', id: '124' },
  { name: 'KY', value: 'Cayman Islands (the)', id: '136' },
  { name: 'CF', value: 'Central African Republic (the)', id: '140' },
  { name: 'TD', value: 'Chad', id: '148' },
  { name: 'CL', value: 'Chile', id: '152' },
  { name: 'CN', value: 'China', id: '156' },
  { name: 'CX', value: 'Christmas Island', id: '162' },
  { name: 'CC', value: 'Cocos (Keeling) Islands (the)', id: '166' },
  { name: 'CO', value: 'Colombia', id: '170' },
  { name: 'KM', value: 'Comoros (the)', id: '174' },
  { name: 'CD', value: 'Congo (the Democratic Republic of the)', id: '180' },
  { name: 'CG', value: 'Congo (the)', id: '178' },
  { name: 'CK', value: 'Cook Islands (the)', id: '184' },
  { name: 'CR', value: 'Costa Rica', id: '188' },
  { name: 'HR', value: 'Croatia', id: '191' },
  { name: 'CU', value: 'Cuba', id: '192' },
  { name: 'CW', value: 'Curaçao', id: '531' },
  { name: 'CY', value: 'Cyprus', id: '196' },
  { name: 'CZ', value: 'Czechia', id: '203' },
  { name: 'CI', value: "Côte d'Ivoire", id: '384' },
  { name: 'DK', value: 'Denmark', id: '208' },
  { name: 'DJ', value: 'Djibouti', id: '262' },
  { name: 'DM', value: 'Dominica', id: '212' },
  { name: 'DO', value: 'Dominican Republic (the)', id: '214' },
  { name: 'EC', value: 'Ecuador', id: '218' },
  { name: 'EG', value: 'Egypt', id: '818' },
  { name: 'SV', value: 'El Salvador', id: '222' },
  { name: 'GQ', value: 'Equatorial Guinea', id: '226' },
  { name: 'ER', value: 'Eritrea', id: '232' },
  { name: 'EE', value: 'Estonia', id: '233' },
  { name: 'SZ', value: 'Eswatini', id: '748' },
  { name: 'ET', value: 'Ethiopia', id: '231' },
  { name: 'FK', value: 'Falkland Islands (the) [Malvinas]', id: '238' },
  { name: 'FO', value: 'Faroe Islands (the)', id: '234' },
  { name: 'FJ', value: 'Fiji', id: '242' },
  { name: 'FI', value: 'Finland', id: '246' },
  { name: 'FR', value: 'France', id: '250' },
  { name: 'GF', value: 'French Guiana', id: '254' },
  { name: 'PF', value: 'French Polynesia', id: '258' },
  { name: 'TF', value: 'French Southern Territories (the)', id: '260' },
  { name: 'GA', value: 'Gabon', id: '266' },
  { name: 'GM', value: 'Gambia (the)', id: '270' },
  { name: 'GE', value: 'Georgia', id: '268' },
  { name: 'DE', value: 'Germany', id: '276' },
  { name: 'GH', value: 'Ghana', id: '288' },
  { name: 'GI', value: 'Gibraltar', id: '292' },
  { name: 'GR', value: 'Greece', id: '300' },
  { name: 'GL', value: 'Greenland', id: '304' },
  { name: 'GD', value: 'Grenada', id: '308' },
  { name: 'GP', value: 'Guadeloupe', id: '312' },
  { name: 'GU', value: 'Guam', id: '316' },
  { name: 'GT', value: 'Guatemala', id: '320' },
  { name: 'GG', value: 'Guernsey', id: '831' },
  { name: 'GN', value: 'Guinea', id: '324' },
  { name: 'GW', value: 'Guinea-Bissau', id: '624' },
  { name: 'GY', value: 'Guyana', id: '328' },
  { name: 'HT', value: 'Haiti', id: '332' },
  { name: 'HM', value: 'Heard Island and McDonald Islands', id: '334' },
  { name: 'VA', value: 'Holy See (the)', id: '336' },
  { name: 'HN', value: 'Honduras', id: '340' },
  { name: 'HK', value: 'Hong Kong', id: '344' },
  { name: 'HU', value: 'Hungary', id: '348' },
  { name: 'IS', value: 'Iceland', id: '352' },
  { name: 'IN', value: 'India', id: '356' },
  { name: 'ID', value: 'Indonesia', id: '360' },
  { name: 'IR', value: 'Iran (Islamic Republic of)', id: '364' },
  { name: 'IQ', value: 'Iraq', id: '368' },
  { name: 'IE', value: 'Ireland', id: '372' },
  { name: 'IM', value: 'Isle of Man', id: '833' },
  { name: 'IL', value: 'Israel', id: '376' },
  { name: 'IT', value: 'Italy', id: '380' },
  { name: 'JM', value: 'Jamaica', id: '388' },
  { name: 'JP', value: 'Japan', id: '392' },
  { name: 'JE', value: 'Jersey', id: '832' },
  { name: 'JO', value: 'Jordan', id: '400' },
  { name: 'KZ', value: 'Kazakhstan', id: '398' },
  { name: 'KE', value: 'Kenya', id: '404' },
  { name: 'KI', value: 'Kiribati', id: '296' },
  { name: 'KP', value: "Korea (the Democratic People's Republic of)", id: '408' },
  { name: 'KR', value: 'Korea (the Republic of)', id: '410' },
  { name: 'KW', value: 'Kuwait', id: '414' },
  { name: 'KG', value: 'Kyrgyzstan', id: '417' },
  { name: 'LA', value: "Lao People's Democratic Republic (the)", id: '418' },
  { name: 'LV', value: 'Latvia', id: '428' },
  { name: 'LB', value: 'Lebanon', id: '422' },
  { name: 'LS', value: 'Lesotho', id: '426' },
  { name: 'LR', value: 'Liberia', id: '430' },
  { name: 'LY', value: 'Libya', id: '434' },
  { name: 'LI', value: 'Liechtenstein', id: '438' },
  { name: 'LT', value: 'Lithuania', id: '440' },
  { name: 'LU', value: 'Luxembourg', id: '442' },
  { name: 'MO', value: 'Macao', id: '446' },
  { name: 'MG', value: 'Madagascar', id: '450' },
  { name: 'MW', value: 'Malawi', id: '454' },
  { name: 'MY', value: 'Malaysia', id: '458' },
  { name: 'MV', value: 'Maldives', id: '462' },
  { name: 'ML', value: 'Mali', id: '466' },
  { name: 'MT', value: 'Malta', id: '470' },
  { name: 'MH', value: 'Marshall Islands (the)', id: '584' },
  { name: 'MQ', value: 'Martinique', id: '474' },
  { name: 'MR', value: 'Mauritania', id: '478' },
  { name: 'MU', value: 'Mauritius', id: '480' },
  { name: 'YT', value: 'Mayotte', id: '175' },
  { name: 'MX', value: 'Mexico', id: '484' },
  { name: 'FM', value: 'Micronesia (Federated States of)', id: '583' },
  { name: 'MD', value: 'Moldova (the Republic of)', id: '498' },
  { name: 'MC', value: 'Monaco', id: '492' },
  { name: 'MN', value: 'Mongolia', id: '496' },
  { name: 'ME', value: 'Montenegro', id: '499' },
  { name: 'MS', value: 'Montserrat', id: '500' },
  { name: 'MA', value: 'Morocco', id: '504' },
  { name: 'MZ', value: 'Mozambique', id: '508' },
  { name: 'MM', value: 'Myanmar', id: '104' },
  { name: 'NA', value: 'Namibia', id: '516' },
  { name: 'NR', value: 'Nauru', id: '520' },
  { name: 'NP', value: 'Nepal', id: '524' },
  { name: 'NL', value: 'Netherlands (the)', id: '528' },
  { name: 'NC', value: 'New Caledonia', id: '540' },
  { name: 'NZ', value: 'New Zealand', id: '554' },
  { name: 'NI', value: 'Nicaragua', id: '558' },
  { name: 'NE', value: 'Niger (the)', id: '562' },
  { name: 'NG', value: 'Nigeria', id: '566' },
  { name: 'NU', value: 'Niue', id: '570' },
  { name: 'NF', value: 'Norfolk Island', id: '574' },
  { name: 'MP', value: 'Northern Mariana Islands (the)', id: '580' },
  { name: 'NO', value: 'Norway', id: '578' },
  { name: 'OM', value: 'Oman', id: '512' },
  { name: 'PK', value: 'Pakistan', id: '586' },
  { name: 'PW', value: 'Palau', id: '585' },
  { name: 'PS', value: 'Palestine, State of', id: '275' },
  { name: 'PA', value: 'Panama', id: '591' },
  { name: 'PG', value: 'Papua New Guinea', id: '598' },
  { name: 'PY', value: 'Paraguay', id: '600' },
  { name: 'PE', value: 'Peru', id: '604' },
  { name: 'PH', value: 'Philippines (the)', id: '608' },
  { name: 'PN', value: 'Pitcairn', id: '612' },
  { name: 'PL', value: 'Poland', id: '616' },
  { name: 'PT', value: 'Portugal', id: '620' },
  { name: 'PR', value: 'Puerto Rico', id: '630' },
  { name: 'QA', value: 'Qatar', id: '634' },
  { name: 'MK', value: 'Republic of North Macedonia', id: '807' },
  { name: 'RO', value: 'Romania', id: '642' },
  { name: 'RU', value: 'Russian Federation (the)', id: '643' },
  { name: 'RW', value: 'Rwanda', id: '646' },
  { name: 'RE', value: 'Réunion', id: '638' },
  { name: 'BL', value: 'Saint Barthélemy', id: '652' },
  { name: 'SH', value: 'Saint Helena, Ascension and Tristan da Cunha', id: '654' },
  { name: 'KN', value: 'Saint Kitts and Nevis', id: '659' },
  { name: 'LC', value: 'Saint Lucia', id: '662' },
  { name: 'MF', value: 'Saint Martin (French part)', id: '663' },
  { name: 'PM', value: 'Saint Pierre and Miquelon', id: '666' },
  { name: 'VC', value: 'Saint Vincent and the Grenadines', id: '670' },
  { name: 'WS', value: 'Samoa', id: '882' },
  { name: 'SM', value: 'San Marino', id: '674' },
  { name: 'ST', value: 'Sao Tome and Principe', id: '678' },
  { name: 'SA', value: 'Saudi Arabia', id: '682' },
  { name: 'SN', value: 'Senegal', id: '686' },
  { name: 'RS', value: 'Serbia', id: '688' },
  { name: 'SC', value: 'Seychelles', id: '690' },
  { name: 'SL', value: 'Sierra Leone', id: '694' },
  { name: 'SG', value: 'Singapore', id: '702' },
  { name: 'SX', value: 'Sint Maarten (Dutch part)', id: '534' },
  { name: 'SK', value: 'Slovakia', id: '703' },
  { name: 'SI', value: 'Slovenia', id: '705' },
  { name: 'SB', value: 'Solomon Islands', id: '090' },
  { name: 'SO', value: 'Somalia', id: '706' },
  { name: 'ZA', value: 'South Africa', id: '710' },
  { name: 'GS', value: 'South Georgia and the South Sandwich Islands', id: '239' },
  { name: 'SS', value: 'South Sudan', id: '728' },
  { name: 'ES', value: 'Spain', id: '724' },
  { name: 'LK', value: 'Sri Lanka', id: '144' },
  { name: 'SD', value: 'Sudan (the)', id: '729' },
  { name: 'SR', value: 'Surivalue', id: '740' },
  { name: 'SJ', value: 'Svalbard and Jan Mayen', id: '744' },
  { name: 'SE', value: 'Sweden', id: '752' },
  { name: 'CH', value: 'Switzerland', id: '756' },
  { name: 'SY', value: 'Syrian Arab Republic', id: '760' },
  { name: 'TW', value: 'Taiwan', id: '158' },
  { name: 'TJ', value: 'Tajikistan', id: '762' },
  { name: 'TZ', value: 'Tanzania, United Republic of', id: '834' },
  { name: 'TH', value: 'Thailand', id: '764' },
  { name: 'TL', value: 'Timor-Leste', id: '626' },
  { name: 'TG', value: 'Togo', id: '768' },
  { name: 'TK', value: 'Tokelau', id: '772' },
  { name: 'TO', value: 'Tonga', id: '776' },
  { name: 'TT', value: 'Trinidad and Tobago', id: '780' },
  { name: 'TN', value: 'Tunisia', id: '788' },
  { name: 'TR', value: 'Turkey', id: '792' },
  { name: 'TM', value: 'Turkmenistan', id: '795' },
  { name: 'TC', value: 'Turks and Caicos Islands (the)', id: '796' },
  { name: 'TV', value: 'Tuvalu', id: '798' },
  { name: 'UG', value: 'Uganda', id: '800' },
  { name: 'UA', value: 'Ukraine', id: '804' },
  { name: 'AE', value: 'United Arab Emirates (the)', id: '784' },
  { name: 'GB', value: 'United Kingdom', id: '826' },
  { name: 'UM', value: 'United States Minor Outlying Islands (the)', id: '581' },
  { name: 'US', value: 'United States of America (the)', id: '840' },
  { name: 'UY', value: 'Uruguay', id: '858' },
  { name: 'UZ', value: 'Uzbekistan', id: '860' },
  { name: 'VU', value: 'Vanuatu', id: '548' },
  { name: 'VE', value: 'Venezuela (Bolivarian Republic of)', id: '862' },
  { name: 'VN', value: 'Viet Nam', id: '704' },
  { name: 'VG', value: 'Virgin Islands (British)', id: '092' },
  { name: 'VI', value: 'Virgin Islands (U.S.)', id: '850' },
  { name: 'WF', value: 'Wallis and Futuna', id: '876' },
  { name: 'EH', value: 'Western Sahara', id: '732' },
  { name: 'YE', value: 'Yemen', id: '887' },
  { name: 'ZM', value: 'Zambia', id: '894' },
  { name: 'ZW', value: 'Zimbabwe', id: '716' },
  { name: 'AX', value: 'Åland Islands', id: '248' }
];
