export const countryList = [
  { id: 4, name: 'af', value: 'Afghanistan' },
  { id: 818, name: 'eg', value: 'Ägypten' },
  { id: 8, name: 'al', value: 'Albanien' },
  { id: 12, name: 'dz', value: 'Algerien' },
  { id: 20, name: 'ad', value: 'Andorra' },
  { id: 24, name: 'ao', value: 'Angola' },
  { id: 28, name: 'ag', value: 'Antigua und Barbuda' },
  { id: 226, name: 'gq', value: 'Äquatorialguinea' },
  { id: 32, name: 'ar', value: 'Argentinien' },
  { id: 51, name: 'am', value: 'Armenien' },
  { id: 31, name: 'az', value: 'Aserbaidschan' },
  { id: 231, name: 'et', value: 'Äthiopien' },
  { id: 36, name: 'au', value: 'Australien' },
  { id: 44, name: 'bs', value: 'Bahamas' },
  { id: 48, name: 'bh', value: 'Bahrain' },
  { id: 50, name: 'bd', value: 'Bangladesch' },
  { id: 52, name: 'bb', value: 'Barbados' },
  { id: 112, name: 'by', value: 'Belarus' },
  { id: 56, name: 'be', value: 'Belgien' },
  { id: 84, name: 'bz', value: 'Belize' },
  { id: 204, name: 'bj', value: 'Benin' },
  { id: 64, name: 'bt', value: 'Bhutan' },
  { id: 68, name: 'bo', value: 'Bolivien' },
  { id: 70, name: 'ba', value: 'Bosnien und Herzegowina' },
  { id: 72, name: 'bw', value: 'Botswana' },
  { id: 76, name: 'br', value: 'Brasilien' },
  { id: 96, name: 'bn', value: 'Brunei' },
  { id: 100, name: 'bg', value: 'Bulgarien' },
  { id: 854, name: 'bf', value: 'Burkina Faso' },
  { id: 108, name: 'bi', value: 'Burundi' },
  { id: 152, name: 'cl', value: 'Chile' },
  { id: 156, name: 'cn', value: 'Volksrepublik China' },
  { id: 188, name: 'cr', value: 'Costa Rica' },
  { id: 208, name: 'dk', value: 'Dänemark' },
  { id: 276, name: 'de', value: 'Deutschland' },
  { id: 212, name: 'dm', value: 'Dominica' },
  { id: 214, name: 'do', value: 'Dominikanische Republik' },
  { id: 262, name: 'dj', value: 'Dschibuti' },
  { id: 218, name: 'ec', value: 'Ecuador' },
  { id: 384, name: 'ci', value: 'Elfenbeinküste' },
  { id: 222, name: 'sv', value: 'El Salvador' },
  { id: 232, name: 'er', value: 'Eritrea' },
  { id: 233, name: 'ee', value: 'Estland' },
  { id: 748, name: 'sz', value: 'Eswatini' },
  { id: 242, name: 'fj', value: 'Fidschi' },
  { id: 246, name: 'fi', value: 'Finnland' },
  { id: 250, name: 'fr', value: 'Frankreich' },
  { id: 266, name: 'ga', value: 'Gabun' },
  { id: 270, name: 'gm', value: 'Gambia' },
  { id: 268, name: 'ge', value: 'Georgien' },
  { id: 288, name: 'gh', value: 'Ghana' },
  { id: 308, name: 'gd', value: 'Grenada' },
  { id: 300, name: 'gr', value: 'Griechenland' },
  { id: 320, name: 'gt', value: 'Guatemala' },
  { id: 324, name: 'gn', value: 'Guinea' },
  { id: 624, name: 'gw', value: 'Guinea-Bissau' },
  { id: 328, name: 'gy', value: 'Guyana' },
  { id: 332, name: 'ht', value: 'Haiti' },
  { id: 340, name: 'hn', value: 'Honduras' },
  { id: 356, name: 'in', value: 'Indien' },
  { id: 360, name: 'id', value: 'Indonesien' },
  { id: 368, name: 'iq', value: 'Irak' },
  { id: 364, name: 'ir', value: 'Iran' },
  { id: 372, name: 'ie', value: 'Irland' },
  { id: 352, name: 'is', value: 'Island' },
  { id: 376, name: 'il', value: 'Israel' },
  { id: 380, name: 'it', value: 'Italien' },
  { id: 388, name: 'jm', value: 'Jamaika' },
  { id: 392, name: 'jp', value: 'Japan' },
  { id: 887, name: 'ye', value: 'Jemen' },
  { id: 400, name: 'jo', value: 'Jordanien' },
  { id: 116, name: 'kh', value: 'Kambodscha' },
  { id: 120, name: 'cm', value: 'Kamerun' },
  { id: 124, name: 'ca', value: 'Kanada' },
  { id: 132, name: 'cv', value: 'Kap Verde' },
  { id: 398, name: 'kz', value: 'Kasachstan' },
  { id: 634, name: 'qa', value: 'Katar' },
  { id: 404, name: 'ke', value: 'Kenia' },
  { id: 417, name: 'kg', value: 'Kirgisistan' },
  { id: 296, name: 'ki', value: 'Kiribati' },
  { id: 170, name: 'co', value: 'Kolumbien' },
  { id: 174, name: 'km', value: 'Komoren' },
  { id: 180, name: 'cd', value: 'Kongo, Demokratische Republik' },
  { id: 178, name: 'cg', value: 'Kongo, Republik' },
  { id: 408, name: 'kp', value: 'Korea, Nord' },
  { id: 410, name: 'kr', value: 'Korea, Süd' },
  { id: 191, name: 'hr', value: 'Kroatien' },
  { id: 192, name: 'cu', value: 'Kuba' },
  { id: 414, name: 'kw', value: 'Kuwait' },
  { id: 418, name: 'la', value: 'Laos' },
  { id: 426, name: 'ls', value: 'Lesotho' },
  { id: 428, name: 'lv', value: 'Lettland' },
  { id: 422, name: 'lb', value: 'Libanon' },
  { id: 430, name: 'lr', value: 'Liberia' },
  { id: 434, name: 'ly', value: 'Libyen' },
  { id: 438, name: 'li', value: 'Liechtenstein' },
  { id: 440, name: 'lt', value: 'Litauen' },
  { id: 442, name: 'lu', value: 'Luxemburg' },
  { id: 450, name: 'mg', value: 'Madagaskar' },
  { id: 454, name: 'mw', value: 'Malawi' },
  { id: 458, name: 'my', value: 'Malaysia' },
  { id: 462, name: 'mv', value: 'Malediven' },
  { id: 466, name: 'ml', value: 'Mali' },
  { id: 470, name: 'mt', value: 'Malta' },
  { id: 504, name: 'ma', value: 'Marokko' },
  { id: 584, name: 'mh', value: 'Marshallinseln' },
  { id: 478, name: 'mr', value: 'Mauretanien' },
  { id: 480, name: 'mu', value: 'Mauritius' },
  { id: 484, name: 'mx', value: 'Mexiko' },
  { id: 583, name: 'fm', value: 'Mikronesien' },
  { id: 498, name: 'md', value: 'Moldau' },
  { id: 492, name: 'mc', value: 'Monaco' },
  { id: 496, name: 'mn', value: 'Mongolei' },
  { id: 499, name: 'me', value: 'Montenegro' },
  { id: 508, name: 'mz', value: 'Mosambik' },
  { id: 104, name: 'mm', value: 'Myanmar' },
  { id: 516, name: 'na', value: 'Namibia' },
  { id: 520, name: 'nr', value: 'Nauru' },
  { id: 524, name: 'np', value: 'Nepal' },
  { id: 554, name: 'nz', value: 'Neuseeland' },
  { id: 558, name: 'ni', value: 'Nicaragua' },
  { id: 528, name: 'nl', value: 'Niederlande' },
  { id: 562, name: 'ne', value: 'Niger' },
  { id: 566, name: 'ng', value: 'Nigeria' },
  { id: 807, name: 'mk', value: 'Nordmazedonien' },
  { id: 578, name: 'no', value: 'Norwegen' },
  { id: 512, name: 'om', value: 'Oman' },
  { id: 40, name: 'at', value: 'Österreich' },
  { id: 626, name: 'tl', value: 'Osttimor' },
  { id: 586, name: 'pk', value: 'Pakistan' },
  { id: 585, name: 'pw', value: 'Palau' },
  { id: 591, name: 'pa', value: 'Panama' },
  { id: 598, name: 'pg', value: 'Papua-Neuguinea' },
  { id: 600, name: 'py', value: 'Paraguay' },
  { id: 604, name: 'pe', value: 'Peru' },
  { id: 608, name: 'ph', value: 'Philippinen' },
  { id: 616, name: 'pl', value: 'Polen' },
  { id: 620, name: 'pt', value: 'Portugal' },
  { id: 646, name: 'rw', value: 'Ruanda' },
  { id: 642, name: 'ro', value: 'Rumänien' },
  { id: 643, name: 'ru', value: 'Russland' },
  { id: 90, name: 'sb', value: 'Salomonen' },
  { id: 894, name: 'zm', value: 'Sambia' },
  { id: 882, name: 'ws', value: 'Samoa' },
  { id: 674, name: 'sm', value: 'San Marino' },
  { id: 678, name: 'st', value: 'São Tomé und Príncipe' },
  { id: 682, name: 'sa', value: 'Saudi-Arabien' },
  { id: 752, name: 'se', value: 'Schweden' },
  { id: 756, name: 'ch', value: 'Schweiz' },
  { id: 686, name: 'sn', value: 'Senegal' },
  { id: 688, name: 'rs', value: 'Serbien' },
  { id: 690, name: 'sc', value: 'Seychellen' },
  { id: 694, name: 'sl', value: 'Sierra Leone' },
  { id: 716, name: 'zw', value: 'Simbabwe' },
  { id: 702, name: 'sg', value: 'Singapur' },
  { id: 703, name: 'sk', value: 'Slowakei' },
  { id: 705, name: 'si', value: 'Slowenien' },
  { id: 706, name: 'so', value: 'Somalia' },
  { id: 724, name: 'es', value: 'Spanien' },
  { id: 144, name: 'lk', value: 'Sri Lanka' },
  { id: 659, name: 'kn', value: 'St. Kitts und Nevis' },
  { id: 662, name: 'lc', value: 'St. Lucia' },
  { id: 670, name: 'vc', value: 'St. Vincent und die Grenadinen' },
  { id: 710, name: 'za', value: 'Südafrika' },
  { id: 729, name: 'sd', value: 'Sudan' },
  { id: 728, name: 'ss', value: 'Südsudan' },
  { id: 740, name: 'sr', value: 'Surivalue' },
  { id: 760, name: 'sy', value: 'Syrien' },
  { id: 762, name: 'tj', value: 'Tadschikistan' },
  { id: 834, name: 'tz', value: 'Tansania' },
  { id: 764, name: 'th', value: 'Thailand' },
  { id: 768, name: 'tg', value: 'Togo' },
  { id: 776, name: 'to', value: 'Tonga' },
  { id: 780, name: 'tt', value: 'Trinidad und Tobago' },
  { id: 148, name: 'td', value: 'Tschad' },
  { id: 203, name: 'cz', value: 'Tschechien' },
  { id: 788, name: 'tn', value: 'Tunesien' },
  { id: 792, name: 'tr', value: 'Türkei' },
  { id: 795, name: 'tm', value: 'Turkmenistan' },
  { id: 798, name: 'tv', value: 'Tuvalu' },
  { id: 800, name: 'ug', value: 'Uganda' },
  { id: 804, name: 'ua', value: 'Ukraine' },
  { id: 348, name: 'hu', value: 'Ungarn' },
  { id: 858, name: 'uy', value: 'Uruguay' },
  { id: 860, name: 'uz', value: 'Usbekistan' },
  { id: 548, name: 'vu', value: 'Vanuatu' },
  { id: 862, name: 've', value: 'Venezuela' },
  { id: 784, name: 'ae', value: 'Vereinigte Arabische Emirate' },
  { id: 840, name: 'us', value: 'Vereinigte Staaten' },
  { id: 826, name: 'gb', value: 'Vereinigtes Königreich' },
  { id: 704, name: 'vn', value: 'Vietnam' },
  { id: 140, name: 'cf', value: 'Zentralafrikanische Republik' },
  { id: 196, name: 'cy', value: 'Zypern' }
];
