export const SUE_MY_REPORTS = 'sueMyReports';
export const SUE_REPORT_VALUES = 'sueReportValues';

export enum SUE_STATUS {
  CLOSED = 'TICKET_STATUS_CLOSED',
  IN_PROCESS = 'TICKET_STATUS_IN_PROCESS',
  INVALID = 'TICKET_STATUS_INVALID',
  OPEN = 'TICKET_STATUS_OPEN',
  WAIT_REQUESTOR = 'TICKET_STATUS_WAIT_REQUESTOR',
  WAIT_THIRDPARTY = 'TICKET_STATUS_WAIT_THIRDPARTY'
}
