name: Accessibility Checks

on:
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  accessibility-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run accessibility tests
        run: npm run test:accessibility
